---
version: '3'
services:
  node0:
    image: mariadb:10.3.15
    container_name: node0
    ports:
      - 43306:3306
    environment:
      MYSQL_DATABASE: galeratest
      MYSQL_ROOT_PASSWORD: test
    command: --wsrep-new-cluster
    volumes:
      - ${PWD}/node0/conf.d/:/etc/mysql/conf.d
      - ${PWD}/node0/db/:/var/lib/mysql
  node1:
    image: mariadb:10.3.15
    restart: always
    container_name: node1
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ${PWD}/node1/conf.d/:/etc/mysql/conf.d
      - ${PWD}/node1/db/:/var/lib/mysql
  node2:
    image: mariadb:10.3.15
    restart: always
    container_name: node2
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ${PWD}/node2/conf.d/:/etc/mysql/conf.d
      - ${PWD}/node2/db/:/var/lib/mysql
  node3:
    image: mariadb:10.3.15
    restart: always
    container_name: node3
    ports:
      - 33306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ${PWD}/node3/conf.d/:/etc/mysql/conf.d
      - ${PWD}/node3/db/:/var/lib/mysql
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - 8080:80
      - 3306:3306
    volumes:
      - ${PWD}/haproxy/:/usr/local/etc/haproxy/
