---
version: '3'
services:
  bunny1:
    image: rabbitmq:3-management
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - ${PWD}/bunny1:/var/lib/rabbitmq
